import { Client } from '@/features/clients/types';

export const clients: Client[] = [
	{
		id: '1',
		fullName: 'John Smith',
		email: 'john.smith@gmail.com',
		company: 'TechCorp',
		phone: '+1 234 567 890',
		status: 'active',
		source: 'Website',
		createdAt: '2024-01-10',
	},
	{
		id: '2',
		fullName: 'Anna Johnson',
		email: 'anna.johnson@gmail.com',
		company: 'DesignPro',
		phone: '+1 555 222 333',
		status: 'lead',
		source: 'LinkedIn',
		createdAt: '2024-02-12',
	},
	{
		id: '3',
		fullName: 'Michael Brown',
		email: 'michael.brown@gmail.com',
		company: 'SalesHub',
		phone: '+1 888 777 666',
		status: 'inactive',
		source: 'Referral',
		createdAt: '2024-03-05',
	},
	{
		id: '4',
		fullName: 'William Thomas',
		email: 'william.thomas@gmail.com',
		company: 'FinEdge',
		phone: '+1 444 111 222',
		status: 'active',
		source: 'Cold Call',
		createdAt: '2024-05-02',
	},
	{
		id: '5',
		fullName: 'Sophia Miller',
		email: 'sophia.miller@gmail.com',
		company: 'BrightSoft',
		phone: '+1 321 765 432',
		status: 'lead',
		source: 'Website',
		createdAt: '2024-04-15',
	},
	{
		id: '6',
		fullName: 'James Wilson',
		email: 'james.wilson@gmail.com',
		company: 'MarketFlow',
		phone: '+1 222 333 444',
		status: 'active',
		source: 'LinkedIn',
		createdAt: '2024-06-01',
	},
	{
		id: '7',
		fullName: 'Olivia Davis',
		email: 'olivia.davis@gmail.com',
		company: 'NovaTech',
		phone: '+1 111 999 888',
		status: 'inactive',
		source: 'Referral',
		createdAt: '2024-01-28',
	},
	{
		id: '8',
		fullName: 'Benjamin Moore',
		email: 'benjamin.moore@gmail.com',
		company: 'CloudSync',
		phone: '+1 777 555 111',
		status: 'lead',
		source: 'Cold Call',
		createdAt: '2024-07-10',
	},
	{
		id: '9',
		fullName: 'Emma Taylor',
		email: 'emma.taylor@gmail.com',
		company: 'PixelWorks',
		phone: '+1 654 987 321',
		status: 'active',
		source: 'Website',
		createdAt: '2024-03-19',
	},
	{
		id: '10',
		fullName: 'Daniel Anderson',
		email: 'daniel.anderson@gmail.com',
		company: 'DataBridge',
		phone: '+1 555 111 999',
		status: 'inactive',
		source: 'LinkedIn',
		createdAt: '2024-02-22',
	},
	{
		id: '11',
		fullName: 'Ava Martinez',
		email: 'ava.martinez@gmail.com',
		company: 'GrowthLab',
		phone: '+1 333 222 111',
		status: 'lead',
		source: 'Website',
		createdAt: '2024-06-18',
	},
	{
		id: '12',
		fullName: 'Ethan Jackson',
		email: 'ethan.jackson@gmail.com',
		company: 'CoreVision',
		phone: '+1 888 444 222',
		status: 'active',
		source: 'Referral',
		createdAt: '2024-05-09',
	},
	{
		id: '13',
		fullName: 'Mia White',
		email: 'mia.white@gmail.com',
		company: 'SkyNetics',
		phone: '+1 999 123 456',
		status: 'inactive',
		source: 'Cold Call',
		createdAt: '2024-04-03',
	},
	{
		id: '14',
		fullName: 'Logan Harris',
		email: 'logan.harris@gmail.com',
		company: 'VisionCraft',
		phone: '+1 222 888 555',
		status: 'active',
		source: 'LinkedIn',
		createdAt: '2024-07-22',
	},
	{
		id: '15',
		fullName: 'Charlotte Clark',
		email: 'charlotte.clark@gmail.com',
		company: 'NextWave',
		phone: '+1 101 202 303',
		status: 'lead',
		source: 'Website',
		createdAt: '2024-03-30',
	},
	{
		id: '16',
		fullName: 'Lucas Lewis',
		email: 'lucas.lewis@gmail.com',
		company: 'InnoSphere',
		phone: '+1 404 505 606',
		status: 'active',
		source: 'Referral',
		createdAt: '2024-06-27',
	},
	{
		id: '17',
		fullName: 'Amelia Walker',
		email: 'amelia.walker@gmail.com',
		company: 'BluePeak',
		phone: '+1 707 808 909',
		status: 'inactive',
		source: 'Cold Call',
		createdAt: '2024-02-08',
	},
	{
		id: '18',
		fullName: 'Henry Hall',
		email: 'henry.hall@gmail.com',
		company: 'ZenByte',
		phone: '+1 808 707 606',
		status: 'lead',
		source: 'LinkedIn',
		createdAt: '2024-05-25',
	},
];
