import { Client } from '@/features/clients/types';

export const clients: Client[] = [
	{
		id: '1',
		fullName: 'John Smith',
		email: 'john.smith@gmail.com',
		company: 'TechCorp',
		phone: '+1 234 567 890',
		status: 'active',
		source: 'Website',
		createdAt: '2024-01-10',
	},
	{
		id: '2',
		fullName: 'Anna Johnson',
		email: 'anna.johnson@gmail.com',
		company: 'DesignPro',
		phone: '+1 555 222 333',
		status: 'lead',
		source: 'LinkedIn',
		createdAt: '2024-02-12',
	},
	{
		id: '3',
		fullName: 'Michael Brown',
		email: 'michael.brown@gmail.com',
		company: 'SalesHub',
		phone: '+1 888 777 666',
		status: 'inactive',
		source: 'Referral',
		createdAt: '2024-03-05',
	},
	{
		id: '4',
		fullName: 'Emily Davis',
		email: 'emily.davis@gmail.com',
		company: 'BrightLabs',
		phone: '+1 202 111 444',
		status: 'active',
		source: 'Website',
		createdAt: '2024-03-18',
	},
	{
		id: '5',
		fullName: 'Daniel Wilson',
		email: 'daniel.wilson@gmail.com',
		company: 'NovaTech',
		phone: '+1 202 555 789',
		status: 'lead',
		source: 'Email Campaign',
		createdAt: '2024-04-01',
	},
	{
		id: '6',
		fullName: 'Sophia Miller',
		email: 'sophia.miller@gmail.com',
		company: 'Marketify',
		phone: '+1 303 456 123',
		status: 'active',
		source: 'LinkedIn',
		createdAt: '2024-04-07',
	},
	{
		id: '7',
		fullName: 'James Taylor',
		email: 'james.taylor@gmail.com',
		company: 'VisionHub',
		phone: '+1 404 888 222',
		status: 'inactive',
		source: 'Referral',
		createdAt: '2024-04-14',
	},
	{
		id: '8',
		fullName: 'Olivia Anderson',
		email: 'olivia.anderson@gmail.com',
		company: 'CloudSync',
		phone: '+1 505 678 901',
		status: 'lead',
		source: 'Website',
		createdAt: '2024-04-20',
	},
	{
		id: '9',
		fullName: 'William Thomas',
		email: 'william.thomas@gmail.com',
		company: 'FinEdge',
		phone: '+1 606 222 111',
		status: 'active',
		source: 'Cold Call',
		createdAt: '2024-05-02',
	},
	{
		id: '10',
		fullName: 'Ava Martinez',
		email: 'ava.martinez@gmail.com',
		company: 'PixelWorks',
		phone: '+1 707 100 200',
		status: 'inactive',
		source: 'Email Campaign',
		createdAt: '2024-05-10',
	},
	{
		id: '11',
		fullName: 'Benjamin Harris',
		email: 'benjamin.harris@gmail.com',
		company: 'CoreStack',
		phone: '+1 808 333 444',
		status: 'active',
		source: 'Website',
		createdAt: '2024-05-16',
	},
	{
		id: '12',
		fullName: 'Mia Clark',
		email: 'mia.clark@gmail.com',
		company: 'InnoWave',
		phone: '+1 909 654 321',
		status: 'lead',
		source: 'LinkedIn',
		createdAt: '2024-05-22',
	},
];
