import { Deal } from '@/features/deals/types';

export const deals: Deal[] = [
	{
		id: '1',
		title: 'Website Redesign',
		clientName: 'John Smith',
		value: 3200,
		status: 'lead',
		manager: 'Roman',
		createdAt: '2024-07-01',
	},
	{
		id: '2',
		title: 'CRM Integration',
		clientName: 'Anna Johnson',
		value: 5400,
		status: 'negotiation',
		manager: 'Roman',
		createdAt: '2024-07-03',
	},
	{
		id: '3',
		title: 'UI Audit',
		clientName: 'Michael Brown',
		value: 1800,
		status: 'won',
		manager: 'Roman',
		createdAt: '2024-07-05',
	},
	{
		id: '4',
		title: 'Landing Page Development',
		clientName: 'Sophia Miller',
		value: 2600,
		status: 'lost',
		manager: 'Roman',
		createdAt: '2024-07-07',
	},
	{
		id: '5',
		title: 'E-commerce Dashboard',
		clientName: 'James Wilson',
		value: 6100,
		status: 'negotiation',
		manager: 'Roman',
		createdAt: '2024-07-09',
	},
	{
		id: '6',
		title: 'Admin Panel Upgrade',
		clientName: 'Emma Taylor',
		value: 4700,
		status: 'lead',
		manager: 'Roman',
		createdAt: '2024-07-11',
	},
	{
		id: '7',
		title: 'Analytics Setup',
		clientName: 'Daniel Anderson',
		value: 2100,
		status: 'won',
		manager: 'Roman',
		createdAt: '2024-07-12',
	},
	{
		id: '8',
		title: 'Support Portal',
		clientName: 'Ava Martinez',
		value: 3900,
		status: 'lost',
		manager: 'Roman',
		createdAt: '2024-07-14',
	},
];
