import { Task } from '@/features/tasks/types';

export const tasks: Task[] = [
	{
		id: '1',
		title: 'Call client about contract',
		description: 'Discuss contract details and timeline',
		status: 'todo',
		priority: 'high',
		dueDate: '2026-03-20',
		assignedTo: 'Roman',
		relatedTo: 'Acme Corp',
		createdAt: '2026-03-10',
	},
	{
		id: '2',
		title: 'Prepare deal presentation',
		description: 'Create slides for the sales meeting',
		status: 'in_progress',
		priority: 'medium',
		dueDate: '2026-03-28',
		assignedTo: 'Roman',
		relatedTo: 'Deal #102',
		createdAt: '2026-03-12',
	},
	{
		id: '3',
		title: 'Send follow-up email',
		description: 'Follow up after demo call',
		status: 'done',
		priority: 'low',
		dueDate: '2026-03-21',
		assignedTo: 'Roman',
		relatedTo: 'John Smith',
		createdAt: '2026-03-11',
	},
	{
		id: '4',
		title: 'Update CRM data',
		description: 'Clean outdated client records',
		status: 'todo',
		priority: 'medium',
		dueDate: '2026-03-18',
		assignedTo: 'Roman',
		relatedTo: 'CRM',
		createdAt: '2026-03-09',
	},
	{
		id: '5',
		title: 'Schedule meeting',
		description: 'Arrange meeting with new client',
		status: 'in_progress',
		priority: 'high',
		dueDate: '2026-03-26',
		assignedTo: 'Roman',
		relatedTo: 'Startup Inc',
		createdAt: '2026-03-15',
	},
	{
		id: '6',
		title: 'Fix UI bug',
		description: 'Resolve layout issue in dashboard',
		status: 'todo',
		priority: 'high',
		dueDate: '2026-03-19',
		assignedTo: 'Roman',
		relatedTo: 'Frontend',
		createdAt: '2026-03-14',
	},
	{
		id: '7',
		title: 'Write documentation',
		description: 'Document API endpoints',
		status: 'done',
		priority: 'medium',
		dueDate: '2026-03-17',
		assignedTo: 'Roman',
		relatedTo: 'API',
		createdAt: '2026-03-08',
	},
	{
		id: '8',
		title: 'Call supplier',
		description: 'Discuss delivery terms',
		status: 'todo',
		priority: 'low',
		dueDate: '2026-03-30',
		assignedTo: 'Roman',
		relatedTo: 'Supplier',
		createdAt: '2026-03-13',
	},
	{
		id: '9',
		title: 'Test new feature',
		description: 'QA testing for tasks module',
		status: 'in_progress',
		priority: 'high',
		dueDate: '2026-03-24',
		assignedTo: 'Roman',
		relatedTo: 'Tasks',
		createdAt: '2026-03-16',
	},
	{
		id: '10',
		title: 'Refactor code',
		description: 'Improve code readability',
		status: 'todo',
		priority: 'medium',
		dueDate: '2026-04-01',
		assignedTo: 'Roman',
		relatedTo: 'Codebase',
		createdAt: '2026-03-18',
	},
	{
		id: '11',
		title: 'Deploy project',
		description: 'Deploy latest version to production',
		status: 'todo',
		priority: 'high',
		dueDate: '2026-03-22',
		assignedTo: 'Roman',
		relatedTo: 'Deployment',
		createdAt: '2026-03-20',
	},
	{
		id: '12',
		title: 'Check analytics',
		description: 'Review user activity data',
		status: 'done',
		priority: 'low',
		dueDate: '2026-03-19',
		assignedTo: 'Roman',
		relatedTo: 'Analytics',
		createdAt: '2026-03-14',
	},
	{
		id: '13',
		title: 'Design new UI',
		description: 'Create layout for new feature',
		status: 'in_progress',
		priority: 'high',
		dueDate: '2026-03-29',
		assignedTo: 'Roman',
		relatedTo: 'Design',
		createdAt: '2026-03-21',
	},
	{
		id: '14',
		title: 'Fix backend bug',
		description: 'Resolve API error',
		status: 'todo',
		priority: 'high',
		dueDate: '2026-03-23',
		assignedTo: 'Roman',
		relatedTo: 'Backend',
		createdAt: '2026-03-19',
	},
	{
		id: '15',
		title: 'Optimize images',
		description: 'Compress assets',
		status: 'done',
		priority: 'low',
		dueDate: '2026-03-16',
		assignedTo: 'Roman',
		relatedTo: 'Assets',
		createdAt: '2026-03-12',
	},
	{
		id: '16',
		title: 'Email marketing',
		description: 'Prepare campaign',
		status: 'todo',
		priority: 'medium',
		dueDate: '2026-04-02',
		assignedTo: 'Roman',
		relatedTo: 'Marketing',
		createdAt: '2026-03-22',
	},
	{
		id: '17',
		title: 'Database backup',
		description: 'Create backup snapshot',
		status: 'done',
		priority: 'high',
		dueDate: '2026-03-18',
		assignedTo: 'Roman',
		relatedTo: 'Database',
		createdAt: '2026-03-10',
	},
	{
		id: '18',
		title: 'Review pull request',
		description: 'Check teammate code',
		status: 'in_progress',
		priority: 'medium',
		dueDate: '2026-03-27',
		assignedTo: 'Roman',
		relatedTo: 'GitHub',
		createdAt: '2026-03-23',
	},
	{
		id: '19',
		title: 'Plan sprint',
		description: 'Define tasks for next sprint',
		status: 'todo',
		priority: 'high',
		dueDate: '2026-03-25',
		assignedTo: 'Roman',
		relatedTo: 'Scrum',
		createdAt: '2026-03-21',
	},
	{
		id: '20',
		title: 'Fix responsive layout',
		description: 'Improve mobile UI',
		status: 'todo',
		priority: 'medium',
		dueDate: '2026-03-24',
		assignedTo: 'Roman',
		relatedTo: 'UI',
		createdAt: '2026-03-22',
	},
	{
		id: '21',
		title: 'Write tests',
		description: 'Add unit tests',
		status: 'in_progress',
		priority: 'high',
		dueDate: '2026-03-31',
		assignedTo: 'Roman',
		relatedTo: 'Testing',
		createdAt: '2026-03-24',
	},
	{
		id: '22',
		title: 'Security audit',
		description: 'Check vulnerabilities',
		status: 'todo',
		priority: 'high',
		dueDate: '2026-03-26',
		assignedTo: 'Roman',
		relatedTo: 'Security',
		createdAt: '2026-03-20',
	},
	{
		id: '23',
		title: 'Update dependencies',
		description: 'Upgrade npm packages',
		status: 'done',
		priority: 'low',
		dueDate: '2026-03-17',
		assignedTo: 'Roman',
		relatedTo: 'Project',
		createdAt: '2026-03-11',
	},
	{
		id: '24',
		title: 'Create landing page',
		description: 'Design marketing page',
		status: 'in_progress',
		priority: 'medium',
		dueDate: '2026-04-03',
		assignedTo: 'Roman',
		relatedTo: 'Website',
		createdAt: '2026-03-23',
	},
	{
		id: '25',
		title: 'Client onboarding',
		description: 'Help new client get started',
		status: 'todo',
		priority: 'high',
		dueDate: '2026-03-21',
		assignedTo: 'Roman',
		relatedTo: 'Client',
		createdAt: '2026-03-18',
	},
];
